### ISSUE TITLE
Want to clarify the results of the reproduction

### ISSUE THREAD

**Issue by ArchyZheng** [stevenyangyj/CoTASP#1]
Hello,

I am trying to reproduce the results posted in the paper, but as my result there are some problems. Sometimes the method can not solve first task, and sometimes the method can not solve the fifth task. I have run several times, the best results is 0.88 but at the most of the time is about 0.8. (I already tried lambda 1e-3 and 1e-3)

**Comment by stevenyangyj** [comment]
I can reproduce it, so could you please share the challenge you met with me?

**Comment by ArchyZheng** [comment]
Thank you for your kind reply. I believe the main issue in reproducing the results might stem from my environment settings, as I am using higher versions of Python and JAX. I am unsure if this could negatively impact the results. 

Could you package your environment in Docker(with continual world and JAX run in CUDA12)? If you could provide a Docker version, I would greatly appreciate it.🙏

**Comment by ArchyZheng** [comment]
OK, I just realize that your posted WANDB also shows the same performance as I tried. The first task and fifth task some times can not bee trained.

**Comment by stevenyangyj** [comment]
I feel like it's a problem caused by the bugs from continual/meta-world benchmark. If you would like to discuss further about this please reach out via email (yijun.steven.yang[AT]gmail.com)

**Comment by ArchyZheng** [comment]
Thank you for your kind reply! I just realized the method of metrics is different, as you mentioned in the WANDB report. Metaworld suggests using an OR-ing operation to count the success rate in one episode. So, there is no confusion here! 

Thank you again for your outstanding article and for taking the time to answer my basic questions!🫡
